import{S as m,i as s}from"./assets/vendor-5ObWk2rO.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const l of a.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&o(l)}).observe(document,{childList:!0,subtree:!0});function t(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function o(e){if(e.ep)return;e.ep=!0;const a=t(e);fetch(e.href,a)}})();const d="52905819-433962418f10cc5e4a65a61ca",g="https://pixabay.com/api/";function h(r){const n=new URLSearchParams({key:d,q:r,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:"40"});return`${g}?${n.toString()}`}function y(r){const n=h(r);return fetch(n).then(t=>{if(!t.ok)throw new Error(`HTTP ${t.status}`);return t.json()}).catch(t=>{throw t})}function b(r){r.innerHTML=""}function L(r,n){const t=n.map(({webformatURL:o,largeImageURL:e,tags:a,likes:l,views:u,comments:p,downloads:f})=>`
        <li class="card">
        <a href="${e}" class="card-link" aria-label="Відкрити зображення у повному розмірі">
        <img class="card-thumb" src="${o}" alt="${S(a)}" loading="lazy" />
        </a>
        <ul class="meta">
        <li><span>Likes</span><b>${l}</b></li>
        <li><span>Views</span><b>${u}</b></li>
        <li><span>Comments</span><b>${p}</b></li>
        <li><span>Downloads</span><b>${f}</b></li>
        </ul>
        </li>`).join("");r.insertAdjacentHTML("beforeend",t)}function c(r,n){r.classList.toggle("is-hidden",!n)}function S(r=""){return String(r).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}const i={form:document.getElementById("search-form"),input:document.getElementById("query"),gallery:document.getElementById("gallery"),loader:document.getElementById("loader")},$=new m(".gallery a",{captionsData:"alt",captionDelay:200,animationSpeed:200});i.form.addEventListener("submit",w);function w(r){r.preventDefault();const n=i.input.value.trim();if(!n){s.warning({title:"Увага",message:"Введіть пошуковий запит.",position:"topRight"});return}c(i.loader,!0),b(i.gallery),y(n).then(t=>{const{hits:o=[]}=t||{};if(!o.length){s.info({title:"Немає результатів",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}L(i.gallery,o),$.refresh()}).catch(t=>{s.error({title:"Помилка",message:`Не вдалося завантажити зображення. ${(t==null?void 0:t.message)||""}`,position:"topRight"})}).finally(()=>{c(i.loader,!1)})}
//# sourceMappingURL=index.js.map
