import{S as m,i as s}from"./assets/vendor-5ObWk2rO.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const f="52905819-433962418f10cc5e4a65a61ca",g="https://pixabay.com/api/";function y(r){const a={key:f,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40};return axios.get(g,{params:a}).then(n=>n.data)}function h(r){r.innerHTML=""}function b(r,a){const n=a.map(({webformatURL:i,largeImageURL:e,tags:t,likes:l,views:u,comments:p,downloads:d})=>`
        <li class="card">
        <a href="${e}" class="card-link" aria-label="Відкрити зображення у повному розмірі">
        <img class="card-thumb" src="${i}" alt="${L(t)}" loading="lazy" />
        </a>
        <ul class="meta">
        <li><span>Likes</span><b>${l}</b></li>
        <li><span>Views</span><b>${u}</b></li>
        <li><span>Comments</span><b>${p}</b></li>
        <li><span>Downloads</span><b>${d}</b></li>
        </ul>
        </li>`).join("");r.insertAdjacentHTML("beforeend",n)}function c(r,a){r.classList.toggle("is-hidden",!a)}function L(r=""){return String(r).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}const o={form:document.getElementById("search-form"),input:document.getElementById("query"),gallery:document.getElementById("gallery"),loader:document.getElementById("loader")},A=new m(".gallery a",{captionsData:"alt",captionDelay:200,animationSpeed:200});o.form.addEventListener("submit",S);function S(r){r.preventDefault();const a=o.input.value.trim();if(!a){s.warning({title:"Увага",message:"Введіть пошуковий запит.",position:"topRight"});return}c(o.loader,!0),h(o.gallery),y(a).then(n=>{const{hits:i=[]}=n||{};if(!i.length){s.info({title:"Немає результатів",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}b(o.gallery,i),A.refresh()}).catch(n=>{s.error({title:"Помилка",message:`Не вдалося завантажити зображення. ${(n==null?void 0:n.message)||""}`,position:"topRight"})}).finally(()=>{c(o.loader,!1)})}
//# sourceMappingURL=index.js.map
